[project]
name = "pyscgen"
version = "0.3.0"
description = "Python AVRO Schema generator which can use multiples example JSONs as input to infer the Schema."
authors = [
    {name = "Florian Salfenmoser", email = "florian.salfenmoser.dev@outlook.de"}
]
readme = "README.md"
license = {text = "BSD-3-Clause"}
requires-python =  ">=3.12,<4.0"
keywords = ["AVRO", "JSON", "merge", "analyze", "pydantic", "model", "schema", "generator"]
dependencies = [
    "pandas>=2.2.3,<3.0",
    "glom>=23.5.0",
    "pydantic>=2.10.3",
    "shortuuid>=1.0.13",
    "pydantic-avro (>=0.10.0)",
]

[project.urls]
Homepage = "https://github.com/Salfiii/pyscgen"
Repository = "https://github.com/Salfiii/pyscgen"

[dependency-groups]
dev = [
    "ruff>=0.14.3",
    "pytest>=8.3.4",
    "fastavro>=1.10.1",
    "coverage>=7.6.9",
]

[tool.ruff]
# Allow lines to be as long as 140.
line-length = 140

[tool.ruff.format]
# Prefer single quotes over double quotes.
quote-style = "double"

[tool.ruff.lint]
select = [
   # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"