[tool.poetry]
name = "pyscgen"
version = "0.2.1"
description = "Python AVRO Schema generator which can use multiples example JSONs as input to infer the Schema."
authors = ["Florian Salfenmoser <florian.salfenmoser.dev@outlook.de>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/Salfiii/pyscgen"
homepage = "https://github.com/Salfiii/pyscgen"
keywords = ["AVRO", "JSON", "merge", "analyze", "pydantic", "model", "schema", "generator"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.3.3"
glom = "^24.11.0"
pydantic = "^1.9.0"
shortuuid = "^1.0.13"
pydantic-avro = "^0.9.1"
fastavro = "^1.12.1"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"
fastavro = "^1.4.9"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
