# https://github.com/pytest-dev/pytest/issues/1978
[pytest]

markers = only: marks tests for dev needs - e.g. allows to run sngle test
addopts = --capture=no -v

norecursedirs = .* dist CVS _darcs {arch} *.egg